Added the linux sections to connecting to the cluster
northeastern-rc/rc-public-documentation pull request #237
Opened 2024-01-31 08:29 UTC by joseph-cooke

2024-01-31 15:44 UTC, trudenkoNE requested changes
⋐(◉▾◉)⋑
[EEEEEEE]

Owl of approval types 'they're all step one'

2024-02-16 17:58 UTC, SerenaCaplins reviewed
looks good to me. Step numbers render correctly in read the docs.

However I think we eventually want to burn down "first steps" So should we be moving the passwordless ssh to within each connecting to cluster section?

2024-02-20 22:27 UTC, SerenaCaplins approved these changes
looks good. First steps is ready to burn down

2024-02-21 20:02 UTC, joseph-cooke commented
First steps is burned down. bashrc content is now in best practices and conda bashrc items are in the conda page.

2024-02-27 19:43 UTC, tketchem14 commented on docs/source/best-practices/shell_environment.md
>  ## The Discovery Shell environment and `.bashrc`
Please capitalize Environment. 
```suggestion
## The Discovery Shell Environment and `.bashrc`
```

2024-02-28 02:17 UTC, Rakshith2605 requested changes
"Update email link formatting in Markdown to hide 'mailto' prefix"

2024-02-28 02:37 UTC, Rakshith2605 requested changes
"Update email link formatting in Markdown to hide 'mailto' prefix"

2024-02-28 02:37 UTC, Rakshith2605 commented on docs/source/best-practices/shell_environment.md
>  Making edits to your `.bashrc` file can result in many issues. Some changes may prevent you from launching apps or executing commands. Modifying your `PATH` variable may result in the inability to us
```suggestion
Making edits to your `.bashrc` file can result in many issues. Some changes may prevent you from launching apps or executing commands. Modifying your `PATH` variable may result in the inability to use basic shell commands (such as `cd` or `ls`) if not done correctly.
```

2024-02-28 02:37 UTC, Rakshith2605 commented on docs/source/best-practices/shell_environment.md
>  The Shell script `.bashrc` is used by Bash to initialize your Shell environment. For example, it is typically used to define aliases, functions, and load modules. Note that environment variables sett
```suggestion
The shell script `.bashrc` is used by `bash` to initialize your Shell environment. For example, it is typically used to define aliases, functions, and load modules. Note that environment variables settings (such as `PATH`) generally go in the `.bash_profile` or `.profile` files. Your `.bashrc`, `.bash_profile`, and `.profile` files live in your `$HOME` directory. You can change your .bashrc with a text editor like [nano](https://www.nano-editor.org/).
```

2024-02-28 02:37 UTC, Rakshith2605 commented on docs/source/best-practices/shell_environment.md
>  Discovery uses a Linux-based Operating System (CentOS), where the Shell program interfaces with the user. Bash (Bourne Again SHell) is one of the most popular Shell implementations, the default Shell
```suggestion
Discovery uses a Linux-based operating system (CentOS), where the shell program interfaces with the user. Bash (Bourne Again SHell) is one of the most popular shell implementations, the default shell on Discovery.
```

2024-03-08 21:30 UTC, joseph-cooke reviewed
The package auto converts the numbered lists into a properly numbered list if 1. is just used so it renders properly. It took me a second to see it also because the source looks differently. (https://northeastern-university-rc-public-documentation--237.com.readthedocs.build/en/237/gettingstarted/connectingtocluster/linux.html)

2024-03-13 13:33 UTC, trudenkoNE approved these changes
⋐(◉▾◉)⋑

lgtm

The systemctl bit in shell_environment imo isn't something that the users would really be using. I think we could save a few lines there.

2024-03-19 16:41 UTC, Rakshith2605 reviewed
Everything looks good.

2024-03-19 16:41 UTC, Rakshith2605 commented on docs/source/best-practices/shell_environment.md
> +# Uncomment the following line if you don't like systemctl's auto-paging feature:
```suggestion
# Uncomment the following line if you don't like SystemCTL's auto-paging feature:
```

2024-03-19 16:41 UTC, Rakshith2605 commented on docs/source/gettingstarted/connectingtocluster/index.md
> +The following sections on this page will guide you on how to connect to the cluster using the command line access using the terminal and the web interface of Open OnDemand. Guides are provided if you
```suggestion
The following sections on this page will guide you on how to connect to the cluster using command-line access using the terminal and the web interface of Open OnDemand. Guides are provided if your personal computer is running Windows, macOS, or Linux.
```

2024-03-25 20:59 UTC, Rakshith2605 approved these changes

2024-03-26 10:35 UTC, merged